name: bustle
description: Collection of widgets and utilities used by lututui's projects
version: 0.0.2
author: lututui
homepage: https://github.com/lututui/bustle-lib

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.1 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true